name: Run Tests

on:
  [push, pull_request]
  
env:
  sec : ${{secrets.HIDDEN_URL}} 
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        run: |
          curl sec > hidden.txt
          echo "Secret retrieved" + sec
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
