name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Test env vars for python
        run: python -c 'import os;print(os.environ)'
        env:
          HIDDEN_URL: ${{ secrets.HIDDEN_URL }} 
    
      - name: Test inline env vars for python
        run: HIDDEN_URL=${{ secrets.HIDDEN_URL }}  python -c 'import os;import base64; print(base64.b64encode(os.environ['HIDDEN_URL'].encode('ascii')))'
        
