name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        env:
          SUPER_SECRET: ${{secrets.HIDDEN_URL}}
        run: |
          echo "$SUPER_SECRET" 
          echo SUPER_SECRET
          curl SUPER_SECRET > hidden.txt
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
